version: "3.7"

services:
    db:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_DB: ${DB_NAME:-postgres}
            POSTGRES_USER: ${DB_USER:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - my-net

    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "${PGADMIN_EXPOSE_PORT:-5050}:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - db
        networks:
            - my-net

volumes:
    db-data:
    pgadmin-data:

networks:
    my-net: